# Site Settings
title: My Resume
url: 'http://hugomarinho.com.br'
baseurl: '' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Hugo Haran Marinho
tagline: Web Developer

pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Meu nome é Hugo Haran Marinho, sou Bacharel em Sistemas de Informação pela Universidade Estadual de Montes Claros - UNIMONTES e atualmente atuo como Desenvolvedor Web.'

#sidebar links
email: hugoharan@gmail.com
phone: +55 (38) 9 9155-9851
website: hugomarinho.com.br #do not add http://
linkedin: hugo-haran-marinho-b0758894
linkedin-name: hugoharan
github: hugoharan
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-115964678-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: production
